trigger:
- main
- develop
- 'release/**'
- 'hotfix/**'


pool:
  vmImage: 'windows-latest'

#variables:
#- group: nils-org-main

steps:
- task: NuGetToolInstaller@1

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '2.2.x'

- task: PowerShell@2
  inputs:
    filePath: 'build.ps1'
    arguments: '-Verbosity Diagnostic'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'BuildArtifacts\Packages\NuGet'
    ArtifactName: 'drop'
    publishLocation: 'Container'