name: Build

on:
  push:
    paths-ignore:
      - "README.md"
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    #mimic "skip_branch_with_pr: true", see https://github.community/t/duplicate-checks-on-push-and-pull-request-simultaneous-event/18012/4
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2022, macos-12 ]
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      MYGET_API_KEY: ${{ secrets.MYGET_API_KEY }}
      MYGET_SOURCE: https://www.myget.org/F/nils-org/api/v2/package
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      NUGET_SOURCE: https://api.nuget.org/v3/index.json
      GITHUB_USERNAME: nils-a
      GITHUB_PASSWORD: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Fetch all tags and branches
        run: git fetch --prune --unshallow

      - name: Cache Tools
        uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4
        with:
          path: tools
          key: ${{ runner.os }}-tools-${{ hashFiles('recipe.cake') }}

      - name: Install .NET
        uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4.0.0
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            6.0.x
            7.0.x

      - name: Build project
        uses: cake-build/cake-action@a6eb054329257c9e70a6c6bf01747ad6e1d9d52b # v1
        with:
          script-path: recipe.cake
          target: CI
          cake-version: 1.3.0

      - name: Upload Issues-Report
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4
        with:
          if-no-files-found: warn
          name: ${{ matrix.os }} issues
          path: BuildArtifacts/report.html

      - name: Upload Packages
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4
        if: runner.os == 'Windows'
        with:
          if-no-files-found: warn
          name: package
          path: BuildArtifacts/Packages/**/*