name: Publish Documentation

on:
  workflow_dispatch:

env:
  WYAM_ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
  # secrets.GITHUB_TOKEN has no permissions to push, sadly.
  WYAM_DEPLOY_BRANCH: 'gh-pages'
  WYAM_DEPLOY_REMOTE: "${{ github.event.repository.html_url }}"

jobs:
  cake:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        fetch-depth: 0 # GitVersion is somewhat irritated when fetch-depth is "1"....
        ref: ${{ github.event.ref }}

    - name: Cache Tools
      uses: actions/cache@e12d46a63a90f2fae62d114769bbf2a179198b5c # v3
      with:
        path: tools
        key: ${{ runner.os }}-doc-tools-${{ hashFiles('recipe.cake') }}

    - name: Publishing documentaiton
      uses: cake-build/cake-action@a6eb054329257c9e70a6c6bf01747ad6e1d9d52b # v1
      with:
        script-path: recipe.cake
        target: Force-Publish-Documentation
        verbosity: Diagnostic
        cake-version: 1.3.0
